- name: install nginx
  ansible.builtin.yum:
    name: nginx
    state: latest

- name: Remove file
  ansible.builtin.file:
    path: cd /usr/share/nginx/html
    state: absent

- name: Copy files
  ansible.builtin.copy:
    src: nginx.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: Remove file
  ansible.builtin.file:
    path: cd /usr/share/nginx/html
    state: directory

- name: Unarchive a file and download
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
    dest: cd /usr/share/nginx/html
    remote_src: yes

- name: Start nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes