- name: redis installation
  hosts: all
  become: true
  tasks:
    - name: installing redis repos
      ansible.builtin.yum:
        name:  https://rpms.remirepo.net/enterprise/remi-release-8.rpm
        state: installed

    - name: disabling module
      ansible.builtin.shell: yum module enable redis:remi-6.2 -y

    - name: installing redis
      ansible.builtin.yum:
        name: redis
        state: latest

    - name: Replace old hostname with new hostname
      ansible.builtin.replace:
        path: /etc/redis.conf
        regexp: '127.0.0.1'
        replace: '0.0.0.0'

    - name: Replace old hostname with new hostname
      ansible.builtin.replace:
        path: /etc/redis/redis.conf
        regexp: '127.0.0.1'
        replace: '0.0.0.0'

    - name: Start redis
      ansible.builtin.service:
        name: redis
        state: started
        daemon_reload: yes

    - name: Enable redis
      ansible.builtin.service:
        name: redis
        enabled: yes