- name: setting hostname
  ansible.builtin.shell: set-hostname {{component}}

- name: install nginx
  ansible.builtin.yum:
    name: nginx
    state: latest

- name: Remove file
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: create app directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name: Copy files
  ansible.builtin.template:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: Copy nginx conf
  ansible.builtin.template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf


#- name: Unarchive a file and download
#  ansible.builtin.unarchive:
#    src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
#    dest: /usr/share/nginx/html
#    remote_src: yes

- name: Unarchive a file and download from nginx
  ansible.builtin.unarchive:
    src: http://{{nexususer}}:{{nexuspassword}}@172.31.80.172:8081/repository/{{component}}/{{component}}-{{appversion}}.zip
    dest: /usr/share/nginx/html
    remote_src: yes
  vars:
    nexususer: "{{lookup('amazon.aws.aws_ssm','nexus.{{env}}.username',region='us-east-1')}}"
    nexuspassword: "{{lookup('amazon.aws.aws_ssm','nexus.{{env}}.password',region='us-east-1')}}"
    appversion: "{{lookup('amazon.aws.aws_ssm','{{component}}.{{env}}.appversion',region='us-east-1')}}"

- name: Start nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes


- name: create nginx directory
  ansible.builtin.file:
    path: /opt/nginx_exporter
    state: directory

- name: Unarchive a file and download nginx node exporter
  ansible.builtin.unarchive:
    src: https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v0.11.0/nginx-prometheus-exporter_0.11.0_linux_amd64.tar.gz
    dest: /opt/nginx_exporter
    remote_src: yes

- name: Copy nginx exporter
  ansible.builtin.template:
    src: nginx-exporter.service
    dest: /etc/systemd/system/nginx_exporter.service

- name: Start nginx-exporter
  ansible.builtin.service:
    name: nginx_exporter
    state: restarted
    enabled: yes

- name: importing filebeat task
  import_role:
    name: elk
    tasks_from: filebeat
