- name: setting hostname
  ansible.builtin.shell: set-hostname {{component}}

- name: install nginx
  ansible.builtin.yum:
    name: nginx
    state: latest

- name: Remove file
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: create app directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name: Copy files
  ansible.builtin.copy:
    src: nginx.conf
    dest: /etc/nginx/default.d/roboshop.conf


- name: Unarchive a file and download
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: Start nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes


- name: create nginx directory
  ansible.builtin.file:
    path: /opt/nginx-exporter
    state: directory

- name: Unarchive a file and download nginx node exporter
  ansible.builtin.unarchive:
    src: https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v0.11.0/nginx-prometheus-exporter_0.11.0_linux_amd64.tar.gz
    dest: /opt/nginx-exporter
    remote_src: yes

- name: Copy nginx exporter
  ansible.builtin.copy:
    src: nginx-exporter.service
    dest: /etc/systemd/system/nginx-exporter.service

- name: Start nginx-exporter
  ansible.builtin.service:
    name: nginx_exporter
    state: restarted
    enabled: yes