- name: Copy elk repo
  ansible.builtin.copy:
    src: elk.repo
    dest: /etc/yum.repos.d/elasticsearch.repo

- name: install filebeat
  ansible.builtin.yum:
    name: filebeat
    state: latest

- name: Start filebeat
  ansible.builtin.service:
    name: filebeat
    state: started

- name: Copying  filebeat yml file
  ansible.builtin.template:
    src: filebeat.yml
    dest: /etc/filebeat/filebeat.yml


- name: Start filebeat
  ansible.builtin.service:
    name: filebeat
    state: restarted
    enabled: yes
    daemon_reload: yes
