- name: Copying shipping conf file
  ansible.builtin.template:
    src: logstash.conf
    dest: /etc/logstash/logstash.conf


- name: Start logstash conf
  ansible.builtin.service:
    name: logstash
    state: restarted
    enabled: yes
    daemon_reload: yes
