- name: Copying prometheus.yml file
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml

- name: restart prometheus
  ansible.builtin.service:
    name: prometheus
    state: started

- name: restart prometheus
  ansible.builtin.service:
    name: prometheus
    state: restarted

- name: Copy alert file
  ansible.builtin.template:
    src: alerts.yml
    dest: /opt/prometheus/alerts.yml