- name: Copy file with owner and permissions
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml

- name: restart prometheus
  ansible.builtin.service:
    name: prometheus
    state: started