- name: installing python
  ansible.builtin.yum:
    name:
      - python36
      - gcc
      - python3-devel
    state: installed

- name: adding user
  ansible.builtin.user:
    name: roboshop

- name: Creating app directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: download app and unzipping
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/payment.zip
    dest: /app
    remote_src: yes

- name: download dependencies
  ansible.builtin.shell: pip3.6 install -r requirements.txt
  args:
    chdir: /app

- name: copying service file
  ansible.builtin.template:
    src: payment.service
    dest: /etc/systemd/system/payment.service

- name: Start payment service
  ansible.builtin.service:
    name: payment
    state: restarted
    enabled: yes
    daemon-reload: yes
